import {Dimensions, Platform} from 'react-native';
import {getBottomSpace, isIphoneX} from 'react-native-iphone-x-helper';
import {moderateScale, scale, verticalScale} from 'react-native-size-matters';

const {width, height} = Dimensions.get('window');

const metrics = {
  marginHorizontal: 10,
  marginVertical: 10,
  section: 25,
  tripleSection: 75,
  marginFifteen: 15,
  baseMargin: 10,
  baseMarginII: 12,
  baseMarginIII: 13,
  twentyFive: 25,
  doubleBaseMargin: 20,
  smallMarginII: 8,
  smallMargin: 5,
  xSmallMargin: 4,
  sixtyFive: 65,
  hundredThirty: 130,
  seventy: 70,
  seventyFive: 75,
  eighty: 80,
  hundred: 100,
  threeHundredFifty: 350,
  fourHundred: 400,
  fourFifty: 450,
  fiveHundred: 500,
  sixHundred: 600,
  ninety: 90,
  doubleSection: 50,
  marginForty: 40,
  thirtyFive: 35,
  marginThirty: 30,
  twentyEight: 28,
  twentyFour: 24,
  minorMargin: 2,
  horizontalLineHeight: 1,
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
  navBarHeight: Platform.OS === 'ios' ? 64 : 54,
  buttonRadius: 4,
  icons: {
    xTiny: 8,
    thirteen: 13,
    tiny: 15,
    small: 20,
    smallI: 21,
    normal: 25,
    medium: 30,
    mediumI: 35,
    mediumX: 40,
    large: 45,
    xl: 50,
    xxl: 55,
  },
  images: {
    small: 20,
    medium: 40,
    large: 60,
    logo: 200,
  },
};

export const MetricsHorizontal = {
  marginHorizontal: scale(10),
  marginVertical: scale(10),
  section: scale(25),
  tripleSection: scale(75),
  marginFifteen: scale(15),
  fifty: scale(50),
  marginSixteen: scale(16),
  baseMargin: scale(10),
  baseMarginII: scale(12),
  baseMarginIII: scale(13),
  baseMarginIV: scale(14),
  twentyFive: scale(25),
  twentySeven: scale(27),
  eighteen: scale(18),
  twentyTwo: scale(22),
  doubleBaseMargin: scale(20),
  smallMarginII: scale(8),
  seven: scale(7),
  nine: scale(9),
  smallMargin: scale(5),
  xxSmallMargin: scale(2),
  xSmallMargin: scale(4),
  hundredThirty: scale(130),
  hundredTen: scale(110),
  hundredTwenty: scale(120),
  hundred: scale(100),
  hundredFive: scale(105),
  threeThirty: scale(330),
  hundredSeventy: scale(170),
  twoThirtyFive: moderateScale(235),
  twoSixty: moderateScale(260),
  ninety: scale(90),
  eighty: scale(80),
  eightyFive: scale(85),
  seventyFive: scale(75),
  seventy: scale(70),
  seventeen: scale(17),
  nineteen: scale(19),
  sixty: scale(60),
  sixtyFiveI: scale(65),
  sixtyEight: scale(68),
  sixtyFive: scale(55),
  doubleSection: scale(50),
  marginFortyFive: scale(45),
  marginForty: scale(40),
  thirtyNine: scale(39),
  marginThirty: scale(30),
  marginThirtyFive: scale(35),
  hundredFifty: scale(150),
  minorMargin: scale(2),
  horizontalLineHeight: scale(1),
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
  navBarHeight: Platform.OS === 'ios' ? 64 : 54,
  buttonRadius: scale(4),
  icons: {
    xTiny: scale(8),
    xxTiny: scale(12),
    tiny: scale(15),
    small: scale(20),
    normal: scale(25),
    medium: scale(30),
    mediumI: scale(40),
    large: scale(45),
    xl: scale(50),
    xli: scale(70),
    xxl: scale(80),
  },
  images: {
    small: scale(20),
    medium: scale(40),
    large: scale(60),
    logo: scale(200),
  },
};

export const MetricsVertical = {
  marginHorizontal: verticalScale(10),
  marginVertical: verticalScale(10),
  section: verticalScale(25),
  tripleSection: verticalScale(75),
  marginFifteen: verticalScale(15),
  marginSixteen: verticalScale(16),
  baseMargin: verticalScale(10),
  baseMarginII: verticalScale(12),
  baseMarginIII: verticalScale(13),
  twelve: verticalScale(12),
  twentyFive: verticalScale(25),
  twentyFour: verticalScale(24),
  twentyTwo: verticalScale(22),
  twentySix: verticalScale(26),
  twentyEight: verticalScale(28),
  twentyOne: verticalScale(21),
  fourHundred: verticalScale(400),
  doubleBaseMargin: verticalScale(20),
  marginSeventeen: verticalScale(17.5),
  smallMargin: verticalScale(5),
  six: verticalScale(6),
  smallMarginII: verticalScale(8),
  smallMarginIII: verticalScale(9),
  xSmallMargin: verticalScale(4),
  hundredThirty: verticalScale(130),
  hundredThirtyFive: verticalScale(135),
  hundredTwentyEight: verticalScale(128),
  sixtyFive: verticalScale(65),
  seventy: verticalScale(70),
  hundredFifty: verticalScale(150),
  hundredSixty: verticalScale(160),
  hundredFortyFive: verticalScale(145),
  hundredForty: moderateScale(140),
  threeHundred: verticalScale(300),
  hundredTwenty: verticalScale(120),
  hundredEighty: verticalScale(180),
  hundredEightyFour: verticalScale(184),
  twoFourty: verticalScale(235),
  twoTwentyFive: verticalScale(225),
  hundred: verticalScale(100),
  hundredTen: verticalScale(110),
  twoHundred: verticalScale(200),
  fiveHundred: verticalScale(500),
  twoHundredFifty: verticalScale(250),
  ninety: verticalScale(90),
  eighty: verticalScale(80),
  eighteen: verticalScale(18),
  eightyFive: verticalScale(85),
  seventyFive: verticalScale(75),
  sixty: verticalScale(60),
  doubleSection: verticalScale(50),
  fiftyFive: verticalScale(55),
  marginForty: verticalScale(40),
  marginFortyFive: scale(45),
  marginThirty: verticalScale(30),
  marginThirtyFive: verticalScale(35),
  marginThirtySix: verticalScale(36),
  marginThirtyThree: verticalScale(33),
  minorMargin: verticalScale(2),
  three: verticalScale(3),
  horizontalLineHeight: verticalScale(1),
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
  navBarHeight: Platform.OS === 'ios' ? 64 : 54,
  buttonRadius: verticalScale(4),
  tabBarHeight: verticalScale(60),
  icons: {
    xTiny: verticalScale(8),
    tiny: verticalScale(15),
    small: verticalScale(20),
    normal: verticalScale(25),
    medium: verticalScale(30),
    large: verticalScale(45),
    xl: verticalScale(50),
  },
  images: {
    small: verticalScale(20),
    medium: verticalScale(40),
    large: verticalScale(60),
    logo: verticalScale(200),
  },
};

export const MetricsMod = {
  marginHorizontal: moderateScale(10),
  eight: moderateScale(8),
  four: moderateScale(4),
  six: moderateScale(6),
  twelve: moderateScale(12),
  fourteen: moderateScale(14),
  twenty: moderateScale(20),
  marginVertical: moderateScale(10),
  section: moderateScale(25),
  twentyThree: moderateScale(23),
  twentyFour: moderateScale(24),
  tripleSection: moderateScale(75),
  marginFifteen: moderateScale(15),
  marginSixteen: moderateScale(16),
  baseMargin: moderateScale(10),
  baseMarginII: moderateScale(12),
  baseMarginIII: moderateScale(13),
  twentyFive: moderateScale(25),
  fifteen: moderateScale(15),
  sixteen: moderateScale(16),
  seventeen: moderateScale(17),
  thirty: moderateScale(30),
  thirtyTwo: moderateScale(32),
  thirtyThree: moderateScale(33),
  thirtyFour: moderateScale(34),
  twentyEight: moderateScale(28),
  thirtyFive: moderateScale(35),
  thirtySix: moderateScale(36),
  thirtyEight: moderateScale(38),
  doubleBaseMargin: moderateScale(20),
  twentyTwo: moderateScale(22),
  twentySeven: moderateScale(27),
  twentyOne: moderateScale(21),
  eighteen: moderateScale(18),
  nineteen: moderateScale(19),
  smallMarginII: moderateScale(8),
  smallMarginI: moderateScale(6),
  buttonBorderRadius: moderateScale(5),
  smallMargin: moderateScale(5),
  xSmallMargin: moderateScale(4),
  xSmallMarginI: moderateScale(3),
  xSmallMarginII: moderateScale(2),
  xSmallMarginIII: moderateScale(1),
  hundredThirty: moderateScale(130),
  hundredThirtyFour: moderateScale(134),
  hundredTwenty: moderateScale(120),
  hundred: moderateScale(100),
  hundredTwo: moderateScale(102),
  hundredFour: moderateScale(104),
  hundredFive: moderateScale(105),
  hundredSix: moderateScale(106),
  hundredSeven: moderateScale(107),
  hundredTen: moderateScale(110),
  hundredForty: moderateScale(140),
  hundredFifty: moderateScale(150),
  hundredSeventy: moderateScale(170),
  hundredSixty: moderateScale(160),
  hundredFiftyFive: moderateScale(155),
  hundredSixtyFive: moderateScale(165),
  hundredSeventyFive: moderateScale(175),
  twoHundred: moderateScale(200),
  twoHundredNine: moderateScale(209),
  twoHundredTwenty: moderateScale(220),
  twoTwentyFive: moderateScale(225),
  hundredEighty: moderateScale(180),
  twoHundredTen: moderateScale(210),
  twoTwentySeven: moderateScale(227),
  twoThirtyFive: moderateScale(235),
  twoThirty: moderateScale(230),
  twoFourty: moderateScale(240),
  twoFourtyFive: moderateScale(245),
  twoEighty: moderateScale(280),
  twoNinety: moderateScale(290),
  twoFifty: moderateScale(250),
  twoFiftyFive: moderateScale(255),
  twoSixty: moderateScale(260),
  twoSixtyFive: moderateScale(265),
  twoEightyFive: moderateScale(285),
  twoSeventyFive: moderateScale(275),
  twoSeventy: moderateScale(270),
  threeHundred: moderateScale(300),
  threeHundredTen: moderateScale(308),
  threeHundredFifteen: moderateScale(315),
  threeTwenty: moderateScale(320),
  threeTwentyTwo: moderateScale(322),
  threeThirty: moderateScale(330),
  threeThirtyFive: moderateScale(335),
  threeForty: moderateScale(340),
  threeFifty: moderateScale(350),
  threeSixty: moderateScale(360),
  threeEighty: moderateScale(380),
  fourHundred: moderateScale(400),
  fiveHundred: moderateScale(500),
  eightHundred: moderateScale(800),
  fourHundredTwenty: moderateScale(420),
  fourHundredSeventy: moderateScale(470),
  fourHundredForty: moderateScale(440),
  fourSixty: moderateScale(460),
  fourEighty: moderateScale(480),
  fifty: moderateScale(50),
  fortyTwo: moderateScale(42),
  forty: moderateScale(40),
  marginFortyFive: scale(45),
  ninety: moderateScale(90),
  followRequestHeight: moderateScale(90),
  ninetyFive: moderateScale(95),
  ninetySeven: moderateScale(97),
  eighty: moderateScale(80),
  eightyTwo: moderateScale(82),
  eightyFive: moderateScale(85),
  eightySeven: moderateScale(87),
  hundredTwentyEight: moderateScale(128),
  seventyFive: moderateScale(75),
  chatListItem: moderateScale(75),
  sixty: moderateScale(60),
  sixtyThree: moderateScale(60),
  sixtyFive: moderateScale(65),
  sixtySeven: moderateScale(67),
  seventy: moderateScale(70),
  hundredNinety: moderateScale(190),
  hundredNinetyFive: moderateScale(195),
  doubleSection: moderateScale(50),
  fiftyTwo: moderateScale(52),
  fiftyFive: moderateScale(55),
  fiftySeven: moderateScale(57),
  marginForty: moderateScale(40),
  fortyFive: moderateScale(45),
  fortyThree: moderateScale(43),
  fortySeven: moderateScale(47),
  marginThirtyFive: moderateScale(35),
  sevenHundred: moderateScale(700),
  marginThirty: moderateScale(30),
  marginThirtyOne: moderateScale(31),
  minorMargin: moderateScale(2),
  minorMarginI: moderateScale(4),
  seven: moderateScale(7),
  nine: moderateScale(9),
  thirteen: moderateScale(13),
  twentySix: moderateScale(26),
  hundredTwentyOne: moderateScale(121),
  hundredTwentyTwo: moderateScale(122),
  marginSeventeen: moderateScale(17.5),
  horizontalLineHeight: moderateScale(1),
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
  navBarHeight: moderateScale(Platform.OS === 'ios' && !isIphoneX() ? 70 : 80),
  buttonRadius: moderateScale(4),
  negativeFifteen: moderateScale(-15),
  negativeTen: moderateScale(-10),
  negativeFive: moderateScale(-5),
  negativeSeven: moderateScale(-7),
  floatingButtonOffsetY: getBottomSpace() + moderateScale(60),
  floatingButtonOffsetX: moderateScale(20),
  tabsHeight: moderateScale(50),
  chatFeedMaxWidth: metrics.screenWidth - moderateScale(100),
  drawerWidth: (80 * metrics.screenWidth) / 100,
  icons: {
    xTiny: moderateScale(15),
    tiny: moderateScale(15),
    small: moderateScale(20),
    medium: moderateScale(30),
    large: moderateScale(45),
    xl: moderateScale(50),
  },
  images: {
    small: moderateScale(20),
    medium: moderateScale(40),
    large: moderateScale(60),
    logo: moderateScale(200),
  },
};

export default metrics;
